### ISSUE TITLE
Authority & Schema Registry - Allow the credential schema pull/push

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/ssi-authority-schema-registry#11]
### Summary
the new service of authority & schema registry should allow to validate credential schemas.
E.g. if a customer gets a credential from an issuer, there need to be the possibility to check if the credential follows the expected schema.
To allow this, we need to store the schema per credential (ideally version based to support multiple versions if needed) and provide a validation possibility.

### Task

- [x] explore how the schemas would get stored
- [ ] implement a schema store prototype (locally)
- [ ] test the prototype with the PO ;)
- [ ] explore what services for schema validation can get provided - two options
  - [ ] provide schemas and user need to validate external
  - [ ] provide customers the possibility to push their credentials and provide back an "ok" or "nok" (see image shared below)
- [ ] store the schemas (schemas added below)

  - [FrameWorkCredential-Schema.json](https://github.com/eclipse-tractusx/ssi-authority-schema-registry/files/14161567/FrameWorkCredential-Schema.json)
  - [DismantlerCredential-Schema.json](https://github.com/eclipse-tractusx/ssi-authority-schema-registry/files/14161568/DismantlerCredential-Schema.json)
  - [MembershipCredential-Schema.json](https://github.com/eclipse-tractusx/ssi-authority-schema-registry/files/14161569/MembershipCredential-Schema.json)
  - [BusinessPartnerCredential-Schema.json](https://github.com/eclipse-tractusx/ssi-authority-schema-registry/files/14161570/BusinessPartnerCredential-Schema.json)

---
---

### Schema Validation
The automatic schema validation based on the stored schema could work as defined below
<img width="971" alt="image" src="https://github.com/eclipse-tractusx/ssi-authority-schema-registry/assets/94133633/410e9fca-5bf7-4c18-9d82-d229665b51e1">

---
---

### Acceptance Criterias

- [ ] implementation done
- [ ] pr created
- [ ] pr reviewed & merged
- [ ] deploy to dev
- [ ] run tests on dev
- [ ] create/update documentation

**Comment by jjeroch** [comment]
Credential schemas to be stored (DRAFT version)
[FrameWorkCredential-Schema.json](https://github.com/eclipse-tractusx/ssi-authority-schema-registry/files/14161563/FrameWorkCredential-Schema.json)
[DismantlerCredential-Schema.json](https://github.com/eclipse-tractusx/ssi-authority-schema-registry/files/14161564/DismantlerCredential-Schema.json)
[MembershipCredential-Schema.json](https://github.com/eclipse-tractusx/ssi-authority-schema-registry/files/14161565/MembershipCredential-Schema.json)
[BusinessPartnerCredential-Schema.json](https://github.com/eclipse-tractusx/ssi-authority-schema-registry/files/14161566/BusinessPartnerCredential-Schema.json)
